- hosts: all
  tasks:
    - block:
        - include_role:
            name: fetch-output
      when:
        - "ansible_connection != 'kubectl'"
        - ansible_user_dir is defined

    - block:
        - include_role:
            name: fetch-output-openshift
      when:
        - "ansible_connection == 'kubectl'"
        - ansible_user_dir is defined

    - import_role:
        name: merge-output-to-logs
      when: ansible_user_dir is defined

- hosts: all
  ignore_errors: yes
  tasks:
    - block:
        - include_role:
            name: remove-build-sshkey
      when:
        - "ansible_connection != 'kubectl'"
        - ansible_user_dir is defined
