- project:
    merge-mode: squash-merge
    default-branch: master
    check:
      jobs:
        - ansible-lint
        - yamllint        
    gate:
      jobs:
        - flake8
    post:
      jobs: []
